# Generated by Django 3.2.6 on 2021-08-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('deptcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('deptname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('projcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('projname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='stuff',
            fields=[
                ('scode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('sname', models.CharField(max_length=10, unique=True)),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.dept')),
                ('projname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.project')),
            ],
        ),
    ]
