# Generated by Django 3.2.6 on 2021-08-25 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companycode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('companyname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('deptname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('jobname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('jobtypecode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('jobtypename', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('productname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statuscode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('statusname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StuffType',
            fields=[
                ('stufftypecode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('stufftypename', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('scode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('sname', models.CharField(max_length=10, unique=True)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.company')),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.dept')),
                ('jobname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.job')),
                ('jobtypename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.jobtype')),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.product')),
                ('statusname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.status')),
                ('stufftypename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.stufftype')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobtypename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.jobtype'),
        ),
    ]
